### PR TITLE
Docs for CLI

### PR DESCRIPTION
**Pull request by t-sasatani**
A quick PR to add docs for CLI using `sphinx-click`. I just noticed I forgot this in the last PR.

### CODE REVIEW

**Comment by t-sasatani** [comment]
Also, I'm curious why the module members (following block) don't appear on the readthedocs page
- https://miniscope-io--33.org.readthedocs.build/en/33/api/stream_daq.html
- https://miniscope-io.readthedocs.io/en/latest/api/stream_daq.html
```
.. automodule:: miniscope_io.stream_daq
    :members:
    :undoc-members:
```

It's a bit confusing that it shows up in my local docs build. I might convert it to an issue later, but I just posted it here for now because it seems minor.

**Review by sneakers-the-rat — APPROVED** [review]

**Comment by t-sasatani** [comment]
The docs aren't showing up on readthedocs for some reason.
It seems like there are some unintended executions, so I replaced `>>>` with `$` to prevent doctests, but it's still happening.
@sneakers-the-rat Could you add me as Maintainers in readthedocs so I can build on random branches?
```
reading sources... [ 68%] api/stream_daq
[24-07-12T03:42:48] WARNING  [miniscope_io.streamDaq] Could not stream_daq.py:39
                             import OpalKelly driver, you can't                 
                             read from FPGA!                                    
                             Check out Opal Kelly's website for                 
                             troubleshooting                                    
                             https://docs.opalkelly.com/fpsdk/g                 
                             etting-started/                                    
reading sources... [ 71%] api/utils
reading sources... [ 75%] api/vendor/index
reading sources... [ 79%] api/vendor/opalkelly
reading sources... [ 82%] cli/main
[24-07-12T03:42:49] WARNING  [miniscope_io.streamDaq] Could not stream_daq.py:39
                             import OpalKelly driver, you can't                 
                             read from FPGA!                                    
                             Check out Opal Kelly's website for                 
                             troubleshooting                                    
                             https://docs.opalkelly.com/fpsdk/g                 
                             etting-started/                                    
[24-07-12T03:42:49] WARNING  [miniscope_io.streamDaq] Could not stream_daq.py:39
                             import OpalKelly driver, you can't                 
                             read from FPGA!                                    
                             Check out Opal Kelly's website for                 
                             troubleshooting                                    
                             https://docs.opalkelly.com/fpsdk/g                 
                             etting-started/     
```

**Comment by sneakers-the-rat** [comment]
idk if this is publicly visible but it looks like unhandled import error in okdev: https://readthedocs.org/projects/miniscope-io/builds/24979334/

what's your rtd username?

**Comment by t-sasatani** [comment]
Oh yes I can see that too.

>what's your rtd username?
It's `t-sasatani`

**Comment by sneakers-the-rat** [comment]
ok invited u. probably a good place to start is adding the exception text and the traceback from that import error into the warning message, and we'll want to either declare `okDev = None` or change the type hints to `'okDev'` rather than the literal `okDev` in `stream_daq`. but ya curious what about the rtd environment can't load that vendored binary bc it should just be ubuntu

**Comment by t-sasatani** [comment]
Ok, I was misunderstanding what `autodoc` does.
It seems like RTD sometimes has problems with binary, so just mocking `_ok.so` in `conf.py` fixed it.

**Pull request merged**
