### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
Depends on: https://github.com/Aharoni-Lab/miniscope-io/pull/14

Add frenly logs that can be configured from environmental variables or a .env file.

Screen Shot 2023-10-24 at 11 58 16 PM

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
Alright, hot on the tails of 14, here's a PR to tidy up the logging :).

@t-sasatani i didn't formally request u as a reviewer bc i figure you have other stuff going on, but you are more than welcome to review if you'd like to :)

**Comment by MarcelMB** [comment]
for my understanding: is this just to add debugging and info messages to the code?

**Comment by sneakers-the-rat** [comment]
yes - we need logging throughout the package, and so i moved the logging instantiation that happened several times in the DAQ module into its own module :). this makes it a bit easier to control the logging as well, you can set the loglevel for stderr and file output separately from a `.env` file or environment variables

**Comment by t-sasatani** [comment]
Thanks! I don't think I'll have time this week, but I have to set this up in my place anyways and can join reviewing/committing from next week if it hasn't been merged by then.

**Comment by t-sasatani** [comment]
I reviewed the tidied up code and confirmed it works with the current hardware, so I will merge this.
I'm planning to send some PRs soon (hopefully by this week) so probably we don't need to hurry for bumping the package version but either way works for me.

**Pull request merged**
